import esbuild from "esbuild";
import process from "process";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const isomorphicGitBrowserEntryPlugin = {
  name: "isomorphic-git-browser-entry",
  setup(build) {
    // Force the main isomorphic-git package to the browser-safe ESM entry so
    // it never pulls in Node built-ins (crypto, stream, etc.).
    build.onResolve({ filter: /^isomorphic-git$/ }, () => ({
      path: path.join(process.cwd(), "node_modules/isomorphic-git/index.js"),
    }));

    // Force the web HTTP transport to the correct file.
    build.onResolve({ filter: /^isomorphic-git\/http\/web$/ }, () => ({
      path: path.join(process.cwd(), "node_modules/isomorphic-git/http/web/index.js"),
    }));

    // Force the Node HTTP transport to its CJS entry.  The module itself uses
    // Node built-ins (https, http, …) which are marked as external below, so
    // they stay as runtime require() calls.  On Electron those resolve fine.
    // The factory is wrapped lazily by esbuild's __commonJS, so the require()
    // calls inside only execute when the factory is actually invoked — which
    // our code only does on desktop (Platform.isMobile === false).
    build.onResolve({ filter: /^isomorphic-git\/http\/node$/ }, () => ({
      path: path.join(process.cwd(), "node_modules/isomorphic-git/http/node/index.cjs"),
    }));
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    // Node built-ins used by isomorphic-git/http/node (via simple-get).
    // Marked external so they stay as runtime require() — resolved by Electron
    // on desktop.  On mobile the code path is never reached so they're never
    // called.
    "http",
    "https",
    "net",
    "tls",
    "zlib",
    "stream",
    "events",
    "url",
    "path",
    "os",
    "crypto",
    "buffer",
    "util",
    "assert",
    "querystring",
    "string_decoder",
  ],
  platform: "browser",
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  mainFields: ["browser", "module", "main"],
  conditions: ["browser", "import", "default"],
  treeShaking: true,
  plugins: [isomorphicGitBrowserEntryPlugin],
  outfile: "main.js",
  minify: prod,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
