import esbuild from "esbuild";
import process from "process";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const isomorphicGitBrowserEntryPlugin = {
  name: "isomorphic-git-browser-entry",
  setup(build) {
    build.onResolve({ filter: /^isomorphic-git$/ }, () => ({
      path: path.join(process.cwd(), "node_modules/isomorphic-git/index.js"),
    }));

    build.onResolve({ filter: /^isomorphic-git\/http\/web$/ }, () => ({
      path: path.join(process.cwd(), "node_modules/isomorphic-git/http/web/index.js"),
    }));
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
  ],
  platform: "browser",
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  mainFields: ["browser", "module", "main"],
  conditions: ["browser", "import", "default"],
  treeShaking: true,
  plugins: [isomorphicGitBrowserEntryPlugin],
  outfile: "main.js",
  minify: prod,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
